version="1.0"

[main]
name.en="Advanced"
name.fr="Paramètres Avancés"
name.de="Erweiterte Einstellungen"
services=["__APP__"]

    [main.advanced]

    
    [main.advanced.explore_user_email]
    ask.en="Should email addresses be show on explore/users page?"
    ask.fr="Les adresses e-mail doivent-elles être affichées sur la page explore/users?"
    ask.de="Sollen Email Adressen auf der Seite explore/users angezeigt werden?"
    type="boolean"
    yes="true"
    no="false"
    default=true
    bind="SHOW_USER_EMAIL:/var/www/__APP__/conf/app.ini"

    [main.advanced.default_keep_email_private]
    ask.en="Should the users email address be hidden in user profile?"
    ask.fr="L'adresse e-mail des utilisateurs doit-elle être masquée dans user profile?"
    ask.de="Soll die E-Mail-Adresse im Nutzerprofil ausgeblendet werden?"
    type="boolean"
    yes="true"
    no="false"
    default=false
    bind="DEFAULT_KEEP_EMAIL_PRIVATE:/var/www/__APP__/conf/app.ini"

    [main.advanced.disable_users_page]
    ask.en="Should the page explore/users be disabled?"
    ask.fr="La page explore/users doit-elle être désactivée ?"
    ask.de="Soll die Seite explore/users deaktiviert werden?"
    type="boolean"
    yes="true"
    no="false"
    default=false
    bind="DISABLE_USERS_PAGE:/var/www/__APP__/conf/app.ini"


    

