version="1.0"

[main]

services = [ "__APP__" ]

name.en = "Main config panel"
name.fr = "Panneau de configuration principal"
name.de = "Hauptmenü für Einstellungen"

help.en = "Here you can easily configure some things about your Gitea instance."
help.de = "Hier kannst du leicht einige Einstellungen deiner Gitea-Instanz anpassen."
help.fr = "Ici tu peux simplement changer des paramètres de ta Gitea instance"

    [main.explore_ui]
    name.fr = "Paramètres de la page Explorateur"
    name.de = "Einstellungen für die Erkunden-Seite"
    name.en = "Settings concerning the Explore page"

        [main.explore_ui.require_signin_view]
        ask.en = "Require sign in to view"
        ask.de = "Aktives Login um Erkunden zu sehen"
        ask.fr = "Besoin de login pour voir la page Explorateur"
        help.en = "Only allow signed in users to view the explore pages"
        help.fr = "L'utilisateur doit s'identifier pour visualiser le contenu."
        help.de = "Nur aktiv eingeloggte Benutzer:innen dürfen die Erkunden-Seite sehen"
        type = "boolean"
        yes = "true"
        no = "false"

        [main.explore_ui.disable_users_page]
        ask.en = "Disable the users explore page?"
        ask.fr = "La page Explorateur/Utilisateurs doit-elle être désactivée?"
        ask.de = "Soll die Seite Erkunden/Benutzer deaktiviert werden?"
        type="boolean"
        yes="true"
        no="false"

        [main.explore_ui.disable_organizations_page]
        ask.en = "Disable the organizations explore page?"
        ask.de = "Soll die Seite Erkunden/ Organisationen deaktiviert werden?"
        ask.fr = "La page Explorateur/ Organisationsd doit-elle être désactivée?"
        type="boolean"
        yes="true"
        no="false"

        [main.explore_ui.disable_code_page]
        ask.en = "Disable the code explore page?"
        ask.de = "Soll die Seite Erkunden/ Repositories deaktiviert werden?"
        ask.fr = "La page Explorateur/ Dépôts doit-elle être désactivée?"
        type="boolean"
        yes="true"
        no="false"

    [main.privacy]
    name.en = "Privacy Settings"
    name.de = "Privatsphäre-Einstellungen"
    name.fr = "Paramètres de confidentialité"

        [main.privacy.show_user_email]
        ask.en="Should email addresses be show on explore/users page?"
        ask.fr="Les adresses e-mail doivent-elles être affichées sur la page Explorateur/ Utilisateurs?"
        ask.de="Sollen Email Adressen auf der Seite Erkunden/ Benutzer angezeigt werden?"
        type="boolean"
        yes="true"
        no="false"

        [main.privacy.default_keep_email_private]
        ask.en="Should the users email address be hidden in user profile?"
        ask.fr="L'adresse e-mail des utilisateurs doit-elle être masquée dans user profile?"
        ask.de="Soll die E-Mail-Adresse im Nutzerprofil ausgeblendet werden?"
        type="boolean"
        yes="true"
        no="false"

    [main.indexing]
    name.en = "Code Indexing"
    name.de = "Code Indexing"
    name.fr = "Code Indexing"

        [main.indexing.repos_indexer_enabled]
        ask.en = "Enable repo indexer"
        ask.de = "Aktiviere Repo Indexer"
        ask.fr = "Activez Repo Indexer"
        help.en = "Indexing code can take a lot of system resources, especially when first enabled or on major Gitea upgrade."
        help.de = "Code Indexing kann viele Systemresourcen beanspruchen, besonders wenn es das erste Mal aktiviert wird oder nach einem Gitea Update."
        help.fr = "L'indexation du code peut consommer beaucoup de ressources système, en particulier lors de la première activation ou après d'un update de Gitea."
        type = "boolean"
        yes="true"
        no="false"

    [main.actions]
    name.en = "Gitea Actions and Webhook"
    name.de = "Gitea Actions und Webhook"
    name.fr = "Gitea Actions et Webhook"

        [main.actions.actions_enabled]
        ask.en = "Enable Gitea Actions"
        ask.de = "Gitea Actions aktivieren"
        ask.fr = "Activez Gitea Actions"
        type = "boolean"
        yes = "true"
        no = "false"

        [main.actions.webhook_allowed_hosts]
        ask.en = "List of hosts allowed to call via webhook"
        ask.de = "Liste von Hosts, die per Webhook angesprochen werden dürfen"
        ask.fr = "Liste des hôtes pouvant être adressés via un webhook"
        help.en = "Webhook can only call allowed hosts for security reasons. Comma separated list (example.com,anotherexample.com)."
        help.de = "Webhook kann nur erlaubte Hosts ansprechen. Durch Komma separierte Liste (beispiel.de,anderesbeispiel.de)."
        help.fr = "Pour des raisons de sécurité, le webhook ne peut appeler que les hôtes autorisés. Liste séparée par des virgules (example.fr, autreexample.fr)."
        visible = "actions.enabled"
        type = "string"
