version="1.0"

[main]
name.en="Advanced"
name.fr="Paramètres Avancés"
name.de="Erweiterte Einstellungen"
    [main.general]
    name.en = "Code indexing"
        [main.general.repos_indexer_enabled]
        ask.en = "Enable repo indexer"
        help.en = "Indexing code can take a lot of system resources, especially when first enabled or on major Gitea upgrade"
        type = "boolean"

    [main.privacy]
    name.en = "Privacy Settings"
    name.de = "Privatsphäre-Einstellungen"
    name.fr = "Paramètres de confidentialité"


        [main.privacy.show_user_email]
        ask.en="Should email addresses be show on explore/users page?"
        ask.fr="Les adresses e-mail doivent-elles être affichées sur la page explore/users?"
        ask.de="Sollen Email Adressen auf der Seite explore/users angezeigt werden?"
        type="boolean"
        yes="true"
        no="false"
                
        [main.privacy.default_keep_email_private]
        ask.en="Should the users email address be hidden in user profile?"
        ask.fr="L'adresse e-mail des utilisateurs doit-elle être masquée dans user profile?"
        ask.de="Soll die E-Mail-Adresse im Nutzerprofil ausgeblendet werden?"
        type="boolean"
        yes="true"
        no="false"
                        
        [main.privacy.disable_users_page]
        ask.en="Should the page explore/users be disabled?"
        ask.fr="La page explore/users doit-elle être désactivée ?"
        ask.de="Soll die Seite explore/users deaktiviert werden?"
        type="boolean"
        yes="true"
        no="false"

       
