#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.6c7d27760137d27ea88c843390c4dbefd7fadb74.name = "1.17.0"
    test_upgrade_from.6c7d27760137d27ea88c843390c4dbefd7fadb74.args.admin = "package_checker"
    test_upgrade_from.6c7d27760137d27ea88c843390c4dbefd7fadb74.args.path = "/"
    test_upgrade_from.6c7d27760137d27ea88c843390c4dbefd7fadb74.args.domain = "domain.tld"

    test_upgrade_from.b327ccd30230ea963a5eef1a566faba76688ac84.name = "1.20.0"
    test_upgrade_from.b327ccd30230ea963a5eef1a566faba76688ac84.args.admin = "package_checker"
    test_upgrade_from.b327ccd30230ea963a5eef1a566faba76688ac84.args.path = "/"
    test_upgrade_from.b327ccd30230ea963a5eef1a566faba76688ac84.args.domain = "domain.tld"

    test_upgrade_from.67d5bc5dc57d8f8793551d7e07c10e8b9d4fe038.name = "1.21.5"
    test_upgrade_from.67d5bc5dc57d8f8793551d7e07c10e8b9d4fe038.args.admin = "package_checker"
    test_upgrade_from.67d5bc5dc57d8f8793551d7e07c10e8b9d4fe038.args.path = "/"
    test_upgrade_from.67d5bc5dc57d8f8793551d7e07c10e8b9d4fe038.args.domain = "domain.tld"

    test_upgrade_from.9f68c61d65babd9ab91a0425e55616f05b547ced.name = "Before helper 2.1"

    # -------------------------------
    # Curl tests to validate that the app works
    # -------------------------------
    [default.curl_tests]
    explore.path = "/"
    explore.logged_on_sso = false
    explore.expect_title = "Explore - Gitea"

    login.path = "/user/login"
    login.logged_on_sso = false
    login.expect_title = "Sign In - Gitea"

    api.path = "/api/v1/user"
    api.logged_on_sso = false
    api.expect_content = '\{"message":"token is required","url":"https://.*/api/swagger"\}'
    api.expect_return_code = 401

    container_registry.base_url = "https://__DOMAIN__"
    container_registry.logged_on_sso = false
    container_registry.path = "/v2"
    container_registry.expect_content = '\{"errors":\[\{"code":"UNAUTHORIZED","message":""\}\]\}'
    container_registry.expect_return_code = 401
