#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.6c7d27760137d27ea88c843390c4dbefd7fadb74.name = "1.17.0"
    test_upgrade_from.b327ccd30230ea963a5eef1a566faba76688ac84.name = "1.20.0"
