#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Load common variables and helpers
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

if systemctl is-active "$app".service --quiet; then
    ynh_print_warn "It's hightly recommended to make your backup when the service is stopped. Please stop $app service with this command before to run the backup 'systemctl stop $app.service'"
fi

ynh_print_info 'Declaring files to be backed up...'

# Copy the app source files
ynh_backup "$install_dir"

# Copy the data files
ynh_backup "$data_dir"

# Copy the conf files
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/etc/fail2ban/jail.d/$app.conf"
ynh_backup "/etc/fail2ban/filter.d/$app.conf"

ynh_backup "/etc/logrotate.d/$app"

ynh_backup "/etc/systemd/system/$app.service"

# Backup logs
ynh_backup "/var/log/$app"

# Dump the database
ynh_print_info "Backing up the MySQL database"
ynh_mysql_dump_db > ./db.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
