#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Load common variables and helpers
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers


if [[ ! "$(systemctl status $app.service)" =~ 'Active: inactive (dead)' ]]; then
    ynh_print_warn --message="It's hightly recommended to make your backup when the service is stopped. Please stop $app service and with this command before to run the backup 'systemctl stop $app.service'"
fi

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message='Declaring files to be backed up...'

# Copy the app source files
ynh_backup --src_path "$install_dir"

# Copy the data files
ynh_backup --src_path "$data_dir" --is_big=1

# Copy the conf files
ynh_backup --src_path "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup --src_path="/etc/fail2ban/jail.d/$app.conf"
ynh_backup --src_path="/etc/fail2ban/filter.d/$app.conf"

ynh_backup --src_path="/etc/logrotate.d/$app"

ynh_backup --src_path "/etc/systemd/system/$app.service"

# Backup logs
ynh_backup --src_path "/var/log/$app"

# Dump the database
ynh_print_info --message="Backing up the MySQL database"
ynh_mysql_dump_db "$db_name" > ./db.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
