#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# IMPORT GENERIC HELPERS
source /usr/share/yunohost/helpers

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

# Import common cmd
source ./experimental_helper.sh
source ./_common.sh

cp -r  /etc/yunohost/apps/${app}/conf ../ # Quick hack for https://github.com/YunoHost/yunohost/pull/427

# RETRIEVE ARGUMENTS
old_domain=$YNH_APP_OLD_DOMAIN
domain=$YNH_APP_NEW_DOMAIN
path_url=$(ynh_normalize_url_path ${YNH_APP_NEW_PATH:-'/'})
app=$YNH_APP_INSTANCE_NAME

dbpass=$(ynh_app_setting_get "$app" mysqlpwd)
admin=$(ynh_app_setting_get "$app" adminusername)
key=$(ynh_app_setting_get "$app" secret_key)
port=$(ynh_app_setting_get "$app" web_port)

#=================================================
# STANDARD MODIFICATIONS
#=================================================

# MODIFY URL IN NGINX CONF
nginx_conf_path=/etc/nginx/conf.d/$old_domain.d/$app.conf

# Change the domain for nginx
# Change the domain for nginx
if [[ "$old_domain" != "$domain" ]]; then
    # Delete file checksum for the old conf file location
    ynh_delete_file_checksum "$nginx_conf_path"
    mv $nginx_conf_path /etc/nginx/conf.d/$domain.d/$app.conf
    # Store file checksum for the new config file location
    ynh_store_file_checksum "/etc/nginx/conf.d/$domain.d/$app.conf"
fi

config_nginx

# Update gitea config
config_gitea

# RELOAD services
ynh_check_starting "INFO] Listen: http://0.0.0.0:" "/var/log/$app/gitea.log"
sleep 1
