#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================

ynh_app_config_apply() {
    _ynh_app_config_apply

    ynh_systemctl --service="$app" --action=restart
}

ynh_app_config_run $1